--- 
- 
  hosts: pythonanywhere
  name: "Deploy to PythonAnywhere"
  remote_user: pawnhall
  gather_facts: False
  tasks: 
    - 
      name: Update code
      shell: "python3 /home/pawnhall/backup_dbs.py ansible-deploy
                && cd /home/pawnhall/pawnhall
                && . /home/pawnhall/.virtualenvs/venv/bin/activate
                && . /home/pawnhall/.virtualenvs/postactivate
                && git pull
                && python manage.py makemigrations && python manage.py migrate
                && python manage.py test --settings='config.settings.test'
                && python manage.py collectstatic --no-input"
